apiVersion: v1
data:
  username: "{{ .Values.ownerName | b64enc }}"
  password: "{{ .Values.ownerPassword | b64enc }}"
kind: Secret
metadata:
  name: {{ .Values.systemName }}-owner
type: kubernetes.io/basic-auth