apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Values.name }}
spec:
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    name: postgresql
    major: "{{ .Values.majorVersion }}"
  instances: "{{ .Values.instances }}"
  storage:
    size: "{{ .Values.storageSize }}"
    resizeInUseVolumes: "true"
    storageClass: csi-hostpath-sc
  resources:
    requests:
      memory: "{{ .Values.memory }}"
      cpu: "{{ .Values.cpu }}"
    limits:
      memory: "{{ .Values.memory }}"
      cpu: "{{ .Values.cpu }}"
  managed:
    roles:
      - name: pgaas
        passwordSecret:
          name: {{ .Values.systemName }}-pgaas-user
        superuser: true
        login: true
  backup:
    volumeSnapshot:
      className: csi-hostpath-snapclass
    barmanObjectStore:
      destinationPath: s3://pgaas-backups/{{ .Values.name }}
      endpointURL: https://s3.yandexcloud.net
      wal:
        compression: bzip2
      s3Credentials:
        accessKeyId:
          name: {{ .Values.systemName }}-s3
          key: accessKey
        secretAccessKey:
          name: {{ .Values.systemName }}-s3
          key: secretKey

  bootstrap:
{{- if .Values.recoveryFromBackup.enabled }}
    recovery:
      backup:
        name: {{ .Values.recoveryFromBackup.backupName }}
{{- else }}
    initdb:
      encoding: 'UTF8'
      localeCollate: '{{ .Values.lcCollate }}'
      localeCType: '{{ .Values.lcCtype }}'
{{- end }}
      database: "{{ .Values.databaseName }}"
      owner: "{{ .Values.ownerName }}"
      secret:
        name: {{ .Values.name }}-owner
  postgresql:
    parameters:
      {{- range $key, $value := .Values.postgresqlParameters }}
      {{$key}}: "{{$value}}"
      {{- end }}