apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: db-{{ .Values.name }}
spec:
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    name: postgresql
    major: "{{ .Values.majorVersion }}"
  instances: "{{ .Values.instances }}"
  storage:
    size: "{{ .Values.storageSize }}"
    resizeInUseVolumes: "false"
  resources:
    requests:
      memory: "{{ .Values.memory }}"
      cpu: "{{ .Values.cpu }}"
    limits:
      memory: "{{ .Values.memory }}"
      cpu: "{{ .Values.cpu }}"
  managed:
    roles:
      - name: pgaas
        passwordSecret:
          name: db-{{ .Values.name }}-pgaas-user
        superuser: true
        login: true
  bootstrap:
    initdb:
      database: "{{ .Values.databaseName }}"
      owner: "{{ .Values.ownerName }}"
      encoding: 'UTF8'
      localeCollate: '{{ .Values.lcCollate }}'
      localeCType: '{{ .Values.lcCtype }}'
      secret:
        name: db-{{ .Values.name }}-owner
  postgresql:
    parameters:
      {{- range $key, $value := .Values.postgresqlParameters }}
      {{$key}}: "{{$value}}"
      {{- end }}