apiVersion: v1
data:
  username: "{{ .Values.ownerName | b64enc  }}"
  password: "{{ .Values.ownerPassword | b64enc  }}"
kind: Secret
metadata:
  name: {{ .Values.name }}-owner
type: kubernetes.io/basic-auth