apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: db-{{ .Values.name }}-route
spec:
  entryPoints:
    - pg
  routes:
    - match: HostSNI(`{{ .Values.name }}.pgaas.ru`)
      services:
{{- if .Values.pooler.enabled }}
        - name: db-{{ .Values.name }}-pooler
{{- else }}
        - name: db-{{ .Values.name }}-rw
{{- end }}
          port: 5432
  tls:
    passthrough: true