apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ .Values.name }}-route
spec:
  entryPoints:
    - pg
  routes:
    - match: HostSNI(`{{ .Values.name }}.pgaas.ru`)
      {{- if .Values.sg.enabled }}
      middlewares:
        - name: {{ .Values.name }}-mdlwr
      {{ - end }}
      services:
        {{- if .Values.pooler.enabled }}
        - name: {{ .Values.name }}-pooler
        {{- else }}
        - name: {{ .Values.name }}-rw
        {{- end }}
          port: 5432
  tls:
    passthrough: true