apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ .Values.systemName }}-route
spec:
  entryPoints:
    - pg
  routes:
    - match: HostSNI(`{{ .Values.systemName }}.pgaas.ru`)
      {{- if eq .Values.sg.enabled "true" }}
      middlewares:
        - name: {{ .Values.systemName }}-mdlwr
      {{- end }}
      services:
        {{- if eq .Values.pooler.enabled "true" }}
        - name: {{ .Values.systemName }}-pooler
        {{- else }}
        - name: {{ .Values.name }}-rw
        {{- end }}
          port: 5432
  tls:
    passthrough: true