{{- if eq .Values.sg.enabled "true" }}
apiVersion: traefik.io/v1alpha1
kind: MiddlewareTCP
metadata:
  name: {{ .Values.systemName }}-mdlwr
spec:
  ipAllowList:
    sourceRange:
      {{- range $ip := .Values.sg.ips }}
      - {{ $ip }}
      {{- end }}
{{- end }}