{{- if .Values.pooler.enabled }}
apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: db-{{ .Values.name }}-pooler
spec:
  cluster:
    name: db-{{ .Values.name }}

  instances: 1
  type: rw
  pgbouncer:
    poolMode: {{ .Values.pooler.poolMode }}
    parameters:
      max_client_conn: "{{ .Values.pooler.maxClientConnections }}"
      default_pool_size: "{{ .Values.pooler.defaultPoolSize }}"
{{- end }}