{{- if eq .Values.backups.enabled "true" }}
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: {{ .Values.name }}
spec:
  schedule: {{ .Values.backups.schedule }}
  method: {{ .Values.backups.method }}
  cluster:
    name: {{ .Values.name }}
{{- end }}