apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: db-pgaas
spec:
  instances: 1
  storage:
    size: 1Gi
  resources:
    requests:
      memory: "600Mi"
    limits:
      memory: "600Mi"
  bootstrap:
    initdb:
      database: "pgaas"
      owner: "pgaas"
      encoding: 'UTF8'
      localeCollate: 'C'
      localeCType: 'C'
      secret:
        name: db-pgaas-secret