apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgaas-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgaas-backend
  template:
    metadata:
      labels:
        app: pgaas-backend
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      serviceAccountName: pgaas-sa
      containers:
        - name: pgaas-backend
          image: "ghcr.io/makeitokay/pgaas_backend:latest"
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: DevelopmentKubernetes
            - name: DOTNET_ENVIRONMENT
              value: DevelopmentKubernetes
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP