apiVersion: v1
kind: Service
metadata:
  name: pgaas-frontend
spec:
  type: ClusterIP
  ports:
    - port: 5173
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: pgaas-frontend
