apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: pgaas
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`api.pgaas.ru`)
      services:
        - name: pgaas-backend
          port: 8080