apiVersion: v1
kind: ServiceAccount
metadata:
  name: pgaas-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pgaas-cluster-role
rules:
  # Namespace resources
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]

  # Helm resources
  - apiGroups: ["helm.toolkit.fluxcd.io"]
    resources: ["helmreleases"]
    verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]

  # PostgreSQL resources (backups and clusters)
  - apiGroups: ["postgresql.cnpg.io"]
    resources: ["backups", "clusters"]
    verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]

  # Pods resources
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pgaas-cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: pgaas-sa
    namespace: infrastructure
roleRef:
  kind: ClusterRole
  name: pgaas-cluster-role
  apiGroup: rbac.authorization.k8s.io